name: books_app
description: Flutter Application based on book exchange

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.11.0
  flutter:
    sdk: flutter
   
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.7.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^7.0.1

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  readmore: ^1.0.0
  google_fonts: ^1.1.1
  google_sign_in: "^4.5.1"
  flutter_login_facebook: ^0.4.2+3
  shared_preferences: ^0.5.12+4

  #Added Provider package
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Barter Books logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
      - assets/
      